[project]
name = "kmera"
version = "0.1.0"
description = ""
authors = [
    { name = "Tu Nombre", email = "tu@email.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"

dependencies = [
    "requests",
    "flask"
]

[tool.uv]  
# Opcional: aquí podrías configurar más opciones de uv