name: 🧪 CI - Python UV

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: 🔍 Lint code with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ❄️ Install uv and create virtual environment
        run: |
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[format]"

      - name: 🔧 Run Ruff Lint
        run: .venv/bin/ruff check src

  test:
    name: 🧪 Run Tests with Coverage
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ❄️ Install uv and create virtual environment
        run: |
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[test]"

      - name: 🧪 Run Tests
        run: .venv/bin/pytest --cov=src tests/ -W ignore::DeprecationWarning --cov-report=xml --cov-report=term-missing
